---
- name: Remove NFS client from workers
  hosts: workers
  become: true
  tasks:

    - name: Unmount NFS share
      mount:
        path: /mnt/nfs/proteins
        state: absent

    - name: Remove NFS client package
      dnf:
        name: nfs-utils
        state: absent

