---
- name: Configure RabbitMQ host
  hosts: host
  become: yes
  roles:
    - host
    - monitoring

- name: Configure Celery workers
  hosts: workers
  become: yes
  roles:
    - workers
    - monitoring

